### ISSUE TITLE
Harmonia Scene.pck packing issue

### ISSUE THREAD

**Issue by RazoRTR** [marcussacana/SiglusSceneManager#1]
First of all, thanks for your great effort to build a program like this! I'm really grateful ^^
About my issue:
So, I dumped Harmonia's executable, SiglusEngine_SteamEN.exe and used your program found the key.
I inserted this key to parsepck.exe and I could extract Scene.pck.
However, I did the same with createpck.exe, but even though I'm sure I did it right, it crashed after
a while when it was packing the files.
![image](https://cloud.githubusercontent.com/assets/4212660/22329342/f5faf8dc-e3d1-11e6-9ab4-fed9a3c4a5f7.png)

Could you look into this?

**Comment by RazoRTR** [comment]
Sorry, the script files' names was in Japanese but my system locale wasn't set to Japanese. That's why it crashed ^^"

I've solved the problem.
Thanks for writing this program. Now we can translate Key's Siglus games to our native language. ^^
We can't thank you enough ^^

**Comment by marcussacana** [comment]
no problem, good lucky with your project man
