### ISSUE TITLE
Hatsuyuki Sakura

### ISSUE THREAD

**Issue by DennisWeyrauch** [marcussacana/SiglusSceneManager#2]
Can confirm that https://vndb.org/v7302 (Hatsuyuki Sakura) works as well

Key: DDE02EF6DE30EF64078B19A84ED3BB14

Note: 
No, I'm not translating. I simply like to have an English Config Panel. (Tested Scene.pck anyway though)

**Comment by DennisWeyrauch** [comment]
PS: You might want to link back to this Fuwa Thread:
https://forums.fuwanovel.net/topic/15427-lamunation-pck-file/

**Comment by marcussacana** [comment]
i know some games don't compatible, but i don't recive any bug report soo i don't like lost time updating the tool
