### ISSUE TITLE
Bigger text & window please...

### ISSUE THREAD

**Issue by 0xh3LL0** [marcussacana/SiglusSceneManager#3]
as we can see from your [video](https://www.youtube.com/watch?v=jYc-uxZRsIg), the tools looks so tiny on the big screen, can you make it with bigger text & window as well...? or at least add an options to change the text size?

**Comment by marcussacana** [comment]
the lastest version of the tool it's easy to use
1 - Compile it
2 - Run the game
3 - Run the tool
4 - Right Click => Extra Tools => Find SiglusEngine Key
5 - Select the game process and wait

6.1 - put the key in the compression.h on in this repo: https://github.com/bitprime/vn_translation_tools/tree/master/rewrite
OR
6.2 - Extract the rar in my video and with a hex edito goto specifed positions in the -keypos.txt and replace with the key detected by my tool.

**Comment by 0xh3LL0** [comment]
uh, no, i guess you miss the point...
i know how to use your tools, and it work well, thanks...
but what i'm asking is, can you make your program with bigger text and window, bcuz its so small...

**Comment by marcussacana** [comment]
I see, i have a bad english hahahahaha
Anyway, my tool isn't to tl projects, you see. this is just a Demo GUI
you can integrate with my tl plataform https://github.com/marcussacana/VNXTLP
he have a "big font" option

This my VNXTLP it's to use my dll's, but you need update the source to work with the SiglusSceneManager
Main I/O file: https://github.com/marcussacana/VNXTLP/blob/master/VNXTLP/Script.cs

**Comment by marcussacana** [comment]
And in the VNXTLP contains a Dictionary.dic and Dictionary.aff, is the LibreOffice Dictionary format, you can use any in this git for sample: https://github.com/LibreOffice/dictionaries (i publish with ptbr dictionary)

**Comment by marcussacana** [comment]
watch the vnxtlp repo, i have plans to add "universal" support to my tools.
