### ISSUE TITLE
Planetarian HD Steam Version

### ISSUE THREAD

**Issue by RazoRTR** [marcussacana/SiglusSceneManager#4]
![image](https://cloud.githubusercontent.com/assets/4212660/25864109/e3e40d3e-34f6-11e7-8efe-4584cdf514c4.png)

Hello, it's me again.

Key decided to use Siglus Engine, instead of Reallive for Planetarian HD's Steam version, which came out only in Chinese for now. I bought it today.

I've tried your tool. I got the key, extracted the Scene.pck, but the scenario files are kinda empty.
When I open a scenario file, it shows a piece of text ("none") instead of where the actual text should be located.
Also, even when I repack the files without even changing anything, whether the .pck file is compressed or not, the game crashes at startup.
Is it because the scenario files are in Chinese, or the key your program found was actually wrong?

Could you solve the problem if I would send you the necessary files?

Thanks for your interest and time!

**Comment by marcussacana** [comment]
Hmm, maybe a update in the ss script format?
after download i can try take a look, thx to report.

**Comment by marcussacana** [comment]
Sorry, i don't found the game to download.

**Comment by RazoRTR** [comment]
It's released only yesterday, so it's normal :D 
I can upload whatever you want. What do you need? Scene.pck, the dump files, and?

**Comment by marcussacana** [comment]
i need the entire game, if is a change in the ss format, i need test before commit a update, i don't like release untested builds

**Comment by RazoRTR** [comment]
I see. I'll upload the game.
The game is not cracked yet, but maybe SmartSteamEmu or something may work.
If none works, I can open Family Share to you, so that you can download and test the game on Steam.

**Comment by marcussacana** [comment]
i think i can crack

**Comment by RazoRTR** [comment]
Alright, I uploaded the game
https://mega.nz/#!a0AwmB4A!F847Pa39t2gxHxkFnkZ9gTjYKM6rfv8uhLg3DcwyESk

**Comment by marcussacana** [comment]
1:00AM now here, but okay! let's download!

**Comment by RazoRTR** [comment]
Sorry, my internet speed isn't fast and I had to sleep :p

**Comment by marcussacana** [comment]
Soo, this isn't a bug, looks the text has stored into new file format, in the dat directory you can found the "text.dbs"... i take a look and looks like a gameexe.dat, but isn't the same format (encryption maybe)?

**Comment by RazoRTR** [comment]
Oh, I see. .dbs fils are database files that could be edited with SQLBase as far as I know. I'll look into it after I come back from school. I'll inform you after that. Thank you very much! ^^

**Comment by RazoRTR** [comment]
As you said, it looks like a new file format.
What I don't understand is, why would Key bother putting an encryption on a Steam release.
I've tried SQLBase, but it seems that text.dbs isn't a supported database file.
I've heard from somewhere that Libreoffice Calc could open .dbs files, so I tried it out too, but it didn't recognize the file.
I've seen the same file format in Harmonia too. In the dat folder, there was a file called ssdb.dbs. It's possibly irrelevant, but would you want me to upload the ssdb.dbs file?

**Comment by marcussacana** [comment]
no thx, The reason to this release have the text into the .dbs seems it's because this game is a import from reallive, i think in new games, the Key don't use this again.

**Comment by RazoRTR** [comment]
I see. It makes sense, considering rewriting the code in Siglus Engine is less efficient and more troubling. Importing the code from Reallive is easier.
Is that .dbs file extractable/repackable somehow?
Also, I suspect that they might use the same method in Little Busters's upcoming Steam release.

**Comment by marcussacana** [comment]
Nothing By now, i don´t can work with this for a time by now, i recommend ask with others hackers who helped in the siglus before.
If you found a tool, if possible, share it.
Sorry.
About the file format, i don´t know much, but looks a compressed + encrypted file, like the gameexe.dat, the .dat have a header of 0x8 bytes, this have 0x4... don´t it´s the same format.

**Comment by RazoRTR** [comment]
Understood.
Thanks for your help so far. You enlightened me very much. I'll ask for help and information on Fuwanovel too then. Thanks for all your help and your time. ^^

**Comment by marcussacana** [comment]
closing by now, if you have any news, please, remember of me.
I Want too have a fully stuff to work with the siglus

**Comment by RazoRTR** [comment]
I've found that .DBS file is a database file format that's used especially in Reallive and Siglus (this time, it's official).
These .dbs files are actually .csv files. There is a tool to convert CSV files to DBS files in RealliveMAX SDK.
However, it doesn't convert DBS files to CSV files.
I've uploaded this program, in case you want to investigate: https://mega.nz/#!i8oXAZCJ!Q-78Q-cOPQL9atIZTq2JGQgt08eSPRy1JZHpKGfTmzk

**Comment by RazoRTR** [comment]
Also, Crass tool seems to be able to extract .dbs files to some degree. Most of the text are unreadable, and the file it gives isn't a CSV file.
For example, I tried to extract dangopedia.dbs from CLANNAD HD via Crass, and I got something like this:
![image](https://cloud.githubusercontent.com/assets/4212660/26253104/de08936e-3cba-11e7-80ea-1e7d81162ef9.png)

**Comment by RazoRTR** [comment]
You can find Crass's source code here: https://github.com/rinrin-/crass

**Comment by marcussacana** [comment]
as i think, this is because the realive import...
https://github.com/rinrin-/crass/blob/c895a5ab425f68b91c2939288698df0df93d3ca1/cui/RealLive/RealLive.cpp#L688

**Comment by marcussacana** [comment]
Support Added.
