### ISSUE TITLE
Any plan to add Reallive XOR key finder support?

### ISSUE THREAD

**Issue by Gezine** [marcussacana/SiglusSceneManager#6]
I'm Trying to find XOR key of Little Busters PE
Any plan to add Reallive XOR key finder support?

**Comment by marcussacana** [comment]
I haven't never planned this, but isn't impossible to do, just a little hard. the problem, i never worked with the reallive, i had no clue where can i found the key manually. if someone give me a proper documentation explaining the RL obfuscation algorithm, i can take a look into this if i see isn't much problematic.

So, basically, I don't plan, but if someone do the dirt work of reverse the engine, I can spend a time writing a automation tool.

**Comment by Gezine** [comment]
Thank you for your reply!
Unfortunately I did try to find the documentation of reallive xor key, but there isn't. :(
Seems like I should reverse it on my own.

**Comment by marcussacana** [comment]
If you will reverse by your own... huh, well, I think can be more easy if you use a game that you already know the key and search in the memory...

**Comment by Gezine** [comment]
Well I have several keys from various games.
Will try to dump process memory and reverse it somehow.

**Comment by RazoRTR** [comment]
I don't know how helpful it'll be, but there's kind of a documentation for the XOR process here: https://www.baka-tsuki.org/project/index.php?title=CLANNADFVProgress

Also take a look at this page:
https://github.com/eglaysher/rldev/pull/3/commits/634b6c5ad1adfae3b94082993295fad75224a843

This page's also helpful:
https://web.archive.org/web/20130115122055/http://forums.novelnews.net/showthread.php?p=68886

**Comment by marcussacana** [comment]
Huh, How I hate work with this RLDev, that shit don't compile with VS...
Now let's see when i will do this, hopeful don't will take one year like the dbs

**Comment by Gezine** [comment]
https://github.com/theappleman/rldev
Super old tool but here is compiled binary with cygwin

https://drive.google.com/file/d/1FccVxvPDTYvZSbL-N3LQBDSPBZ73VtlC/view?usp=sharing

attached cygwin itself is super old version.
I only tested it on winxp and win7 32bit

built-in XOR keys in rldev
https://github.com/theappleman/rldev/blob/master/lib/game.cfg

Hope this helped

**Comment by Gezine** [comment]
I just got XOR key of Little busters PE (LBPE).
Used simple trick. (Not fancy though)
XOR'ing decrypted LBEX reallive bytecode script file to encrypted LBPE reallive bytecode script file
Fortunately LBEX's SEEN9600 and LBPE's SEEN9600 was same file (file size matched byte to byte)
XORed these two and I got XOR key.
This method is not for universal but my object was getting XOR key of LBPE.
So issue closed

**Comment by marcussacana** [comment]
If possible publish the key for future reference of any possible translator.
that said, your information is basically enough to get the key.

**Comment by Gezine** [comment]
Don't know where Should I put this thing, but here it is
Put this to /usr/local/share/rldev/lib/game.cfg

game LBPE "Little Busters! PE" by Key
 for RealLive 1.6.0.1
 using key from 256 for 257:
  0xA8 0x28 0xFD 0x64 0xA9 0x23 0x77 0x06
  0xFA 0x39 0x88 0x3F 0x6C 0x13 0xA2 0xF0

Hope this helped other translator.
