### ISSUE TITLE
Issue with Planetarian Snow Globe and Lunaria Keys

### ISSUE THREAD

**Issue by KitaroBoi** [marcussacana/SiglusSceneManager#8]
Hello! 

Upon trying to replace the keys for tools to work with the scripts for both planetarian ~Snow Globe~ and LUNARiA -Virtualized Moonchild- it works fine all the way up to decrypting the dumping the scripts, however, upon repacking it crashes the the game or only appears in Japanese. I made sure I was in Japanese Locale and did everything right, would you happen to know what the problem is. 

(Image below shows what happens when we repack) 
![unknown (1)](https://user-images.githubusercontent.com/59377584/147375940-3d9b10d7-481f-43f5-92c4-c15b920c94fb.png)

**Comment by marcussacana** [comment]
This is a problem with the createpck tool, try the sigluspck tool by binaryfail, I don't have with me right now.

**Comment by KitaroBoi** [comment]
I can't seem the find the page to open an issue there... can I please have a link to be directed there so I can see what's wrong?

**Comment by marcussacana** [comment]
here, I found it
[SiglusPCK - Manual Key.rar](https://github.com/marcussacana/SiglusSceneManager/files/7791719/SiglusPCK.-.Manual.Key.rar.zip)
extract the .pck again, don't try repack the extracted files with the old tool
