### ISSUE TITLE
Is there a way to use only SiglusPatcher for Siglusengine version up without debugger mode?

### ISSUE THREAD

**Issue by freakyboy1** [marcussacana/SiglusSceneManager#9]
I want only Siglusengine version up without debugger mode.
Can I get or slefmade SiglusPatcher.exe that are excluded SiglusDebugger3.dll?

**Comment by marcussacana** [comment]
The game will works even if you just delete the SiglusDebugger3.dll

**Comment by freakyboy1** [comment]
> 
Thank you for your answer.
But in the sigluspatcher.zip you released, there are only sigluspatcher.exe and sigluspatcher.pdb
I can't delete it.

**Comment by freakyboy1** [comment]
I solved it. Thank you!!
